BfArM-MVH/grz-tools

src/grz_cli/models/v1_0_0/metadata.py
src/grz_cli/parser.py
tests/test_parser.py

- during threshold checks, if an error occurs, print a more informative message
- when a ValidationError occurs during model instantiation, only report the ValidationErrors, do not include the stacktrace

chore: Improve error reporting

---

src/grz_cli/cli.py

fix: decryption log message should read "decryption", not "encryption"

---

pyproject.toml

setuptools will drop support for this format on 2026-02-18.
See [the docs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files) for more details.
Triggered by a warning in the [bioconda build output](https://github.com/bioconda/bioconda-recipes/actions/runs/14493734614/job/40656258678#step:9:417).

chore: use modern license specification format

---

src/grz_cli/cli.py

Nothing fancy, but fulfills the basic needs of #29

feat: introduce `submit` subcommand for sequentially running validate, encrypt and upload

---

resources/config.yaml
src/grz_cli/models/config.py

This makes the S3 credentials optional in the config file, allowing boto3 to read from the usual S3 environment variables if missing from the config file.
Resolves https://github.com/BfArM-MVH/grz-cli/issues/87

feat: fallback to environment for S3 credentials

---

.github/workflows/docker.yml
.github/workflows/pypi.yml

Causes failures with PyPI deploys but also mostly redudant for Docker.

build: remove release trigger for PyPI and Docker workflows

---

src/grz_cli/commands/common.py

Since the submission is downloaded into the top level of the specified folder it should be an error if it already exists, as another submission may be present in that folder.

fix: require nonexistent submission download directory

---

src/grz_cli/workers/submission.py

Nanopore reads are also in FASTQ files but don't all have identical read lengths in raw data like Illumina.

fix: skip strict read length check for ONT reads

---

.github/workflows/ci.yml
packages/grz-cli/pyproject.toml
packages/grz-pydantic-models/pyproject.toml
packages/grz-pydantic-models/uv.lock
packages/grzctl/pyproject.toml
packages/grzctl/tests/test_cli.py
packages/grzctl/uv.lock
pyproject.toml

* migrates from workspaces to plain subpackages to enable isolated package testing environments
* enable CI to test subpackages individually

build(repo): drop workspaces to enable per-package CI

---

packages/grzctl/src/grzctl/commands/pruefbericht.py

Adds a `--dry-run` option to `pruefbericht`, such that the Pruefbericht is only built (and printed to stdout), not submitted.
If combined with `--json`, outputs the Pruefbericht as JSON.
For `--dry-run` without `--json`, omits the wrapping `Pruefbericht`.
Resolves https://github.com/BfArM-MVH/grz-tools/issues/111

feat(grzctl): Add --dry-run option to print pruefbericht, then exit

---

packages/grz-common/src/grz_common/workers/submission.py

Until the upstream schema is updated this will help guide users towards the right relative path.
Related to https://github.com/BfArM-MVH/grz-tools/issues/106

fix(grz-common): improve missing file error message

---

packages/grz-db/src/grz_db/models/submission.py
packages/grzctl/src/grzctl/commands/db.py
tests/cli/test_db.py

Previously, the `db submission add` command required knowing the tanG / pseudonym before knowing them. Therefore we introduce the `db submission modify SUBMISSION_ID tanG/pseudonym VALUE` command here.
Resolves #188 and #200

fix(grzctl,grz-db): Add `db submission modify` to allow setting tanG/pseudonym

---

packages/grz-cli/src/grz_cli/cli.py
packages/grz-common/src/grz_common/workers/submission.py
packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/__init__.py
packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
packages/grzctl/src/grzctl/cli.py
tests/mock_files/submissions/valid_submission/metadata/metadata.json

* also remove supported metadata schema version display from grzctl as it will be all current and prior versions.
Resolves https://github.com/BfArM-MVH/grz-tools/issues/112
Will remove deprecated stuff in later PR.

refactor(grz-pydantic-models,grz-cli,grzctl): Match multiple schema URLs

---

packages/grz-db/src/grz_db/models/author.py
packages/grzctl/src/grzctl/commands/db.py

Resolves https://github.com/BfArM-MVH/grz-tools/issues/190
Comment is printed next to successful verification, so no longer required to match data steward ID in database

refactor(grz-db,grzctl): fall back to all public keys to verify database changes

---

packages/grz-common/src/grz_common/workers/download.py
packages/grzctl/src/grzctl/commands/clean.py
packages/grzctl/src/grzctl/commands/list_submissions.py
packages/grzctl/src/grzctl/models/config.py
tests/cli/test_clean.py

Keeps an empty metadata.json in the inbox to prevent future re-uploads of the same submission. Also allows checking if the submission has been cleaned.
Resolves https://github.com/BfArM-MVH/grz-tools/issues/194

feat(grzctl,grz-common): use marker files while cleaning

---

.github/workflows/pypi.yml

Forgot to modify this when dropping uv workspaces usage.

ci(repo): fix package build

---

packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
packages/grz-pydantic-models/tests/resources/example_metadata/wgs_trio/v1.1.7.earlyBCException.json
packages/grz-pydantic-models/tests/test_metadata.py

June 15, 2025 is allowed and only mother/father donors can use this.
Resolves https://github.com/BfArM-MVH/grz-tools/issues/275

fix(grz-pydantic-models): Fix conditions for consent exemption

---

packages/grz-cli/src/grz_cli/commands/validate.py
packages/grz-common/src/grz_common/workers/worker.py
tests/cli/test_validate.py

This was an unintentional API break. Users shouldn't be required to pass `--no-grz-check` to continue working with `grz-cli` as before.

fix(grz-common): correctly fallback without grz-check

---

packages/grz-cli/pyproject.toml
packages/grzctl/pyproject.toml

* bump grz-common to fallback without grz-check correctly
* bump grz-pydantic-models to allow non-index donors to fail thresholds

fix(grzctl,grz-cli): bump dependencies

---

packages/grz-common/pyproject.toml

Uses the new submission_id property of GrzSubmissionMetadata

fix(grz-common): bump grz-pydanic-models version

---

.github/workflows/ci.yml
.github/workflows/pypi.yml

Resolves https://github.com/BfArM-MVH/grz-tools/issues/290
ci(repo): use env to define uv version for PyPI build

ci(repo): bump uv to 0.8

---

tests/cli/test_db.py
tests/cli/test_report.py

This causes environment leakage across tests because os.environ is global to the whole process and these are unnecessary anyways.

test(repo): drop os.environ usage from tests

---

tests/cli/test_pruefbericht.py
tests/mock_files/submissions/valid_submission/metadata/metadata.json

An LE had the idea to set the mock submission type to "test" in case of accidental upload, or testing real uploads, and I agreed this was good now that we have the "test" submission type.

test(repo): change mock submission type to test

---

packages/grz-pydantic-models/src/grz_pydantic_models/mii/consent.py
packages/grz-pydantic-models/tests/test_metadata.py

Resolves https://github.com/BfArM-MVH/grz-tools/issues/391

fix(grz-pydantic-models): accept consent objects with no subprovisions

---

packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/__init__.py
packages/grzctl/src/grzctl/commands/pruefbericht.py
tests/cli/test_pruefbericht.py

Resolves #392 
Introduces `grzctl pruefbericht generate` and `grzctl pruefbericht submit`:
```sh
grzctl pruefbericht generate from-submission-dir $submission_dir > foo.json
grzctl pruefbericht generate from-metadata $submittion_dir/metadata/metadata.json > foo.json
```
(perhaps we only need either one)
Initially I made use of options, but those were redundant with the subcommand naming, so changed to arguments. That, however, makes it a bit inconsistent with the `submit` subcommand:
```sh
grzctl pruefbericht submit --pruefbericht-file foo.json
```
which does still use the option style for explicitness.

feat(grzctl)!: make pruefbericht submission a two step process
