BfArM-MVH/grz-tools

- pyproject.toml
See https://github.com/astral-sh/uv/issues/9513 and https://github.com/pypa/setuptools/issues/4759 for more information.
> chore: workaround setuptools license-file issue

- pyproject.toml
- src/grz_cli/cli.py
- uv.lock
Closes https://github.com/BfArM-MVH/grz-cli/issues/47
Open to suggestions on alternative formatting of the message.
> feat: report supported metadata schema versions with cli version

- pyproject.toml
- src/grz_cli/bam_validation.py
- src/grz_cli/parser.py
- tests/resources/reads/README.md
- tests/resources/reads/valid_HiFi.bam
- tests/test_bam_validation.py
- uv.lock
Depends on https://github.com/BfArM-MVH/grz-cli/pull/53.
Closes #12
Closes #13 
Closes #14
> Long read support

- uv.lock
Minimum boto3 version was mis-specified / not synced.
> build: update uv.lock 

- resources/config.yaml
Closes https://github.com/BfArM-MVH/grz-cli/issues/66
> docs: add new S3 option to example config

- resources/config.yaml
- src/grz_cli/models/config.py
- src/grz_cli/upload.py
- increase minimum multipart chunksize to 256MiB
- make multipart chunksize configurable (but still adjust if number of chunks exceeds backend limits)
> perf: Increase minimum chunksize

- .gitignore
- pyproject.toml
- src/grz_cli/cli.py
- src/grz_cli/download.py
- src/grz_cli/transfer.py
- src/grz_cli/upload.py
- uv.lock
Resolves https://github.com/BfArM-MVH/grz-cli/issues/75
Example: `grz-cli download --submission-id $(grz-cli list --json | jq '.[0].id')`
~Still needs cleaning, all of this data munging should be abstracted out of `cli.py` for re-use in watchdog.~
> feat: command to list inbox submissions

- src/grz_cli/upload.py
Resolves https://github.com/BfArM-MVH/grz-cli/issues/82
> feat: block fully-uploaded submissions from being reuploaded

- src/grz_cli/workers/submission.py
Resolves https://github.com/BfArM-MVH/grz-cli/issues/60
> feat: cap filename length to prevent upload errors

- pyproject.toml
- src/grz_cli/cli.py
- src/grz_cli/commands/pruefbericht.py
- src/grz_cli/models/config.py
- tests/cli/test_pruefbericht.py
- uv.lock
Resolves https://github.com/BfArM-MVH/grz-cli/issues/80
> feat: add command to submit Prüfbericht

- src/grz_cli/commands/pruefbericht.py
- tests/cli/test_pruefbericht.py
Also add better logging to see what's happening.
> Fix expired Prüfbericht token response status code

- src/grz_cli/workers/worker.py
Thread parameter was overridden with default parameter in S3BotoUploadWorker
> fix: threads parameter was ignored in upload and download

- packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
- packages/grz-pydantic-models/tests/test_metadata.py
- tests/test_file_progress_logging.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/143
> fix(grz-pydantic-models): require valid file extensions for QC pipeline

- pyproject.toml
- uv.lock
Depends on https://github.com/BfArM-MVH/grz-tools/pull/163
> test(repo): use editable installs of subpackages in uv

- packages/grz-cli/pyproject.toml
- packages/grz-cli/uv.lock
- packages/grz-common/pyproject.toml
- packages/grz-common/uv.lock
- packages/grz-db/pyproject.toml
- packages/grz-db/uv.lock
- packages/grz-pydantic-models/pyproject.toml
- packages/grz-pydantic-models/uv.lock
- packages/grzctl/pyproject.toml
- packages/grzctl/uv.lock
Fixes CI failures in testing changed packages due to missing tox.
> ci(repo): add tox to all packages

- packages/grz-db/src/grz_db/models/author.py
> fix(grzctl): improve error message on incorrect passphrase for author's private key

- packages/grz-db/src/grz_db/models/author.py
- packages/grz-db/src/grz_db/models/base.py
> fix(grz-db): Ensure author keys are ed25519

- packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
> fix(grz-cli,grz-pydantic-models): Disallow empty sequence data

- packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
- packages/grz-pydantic-models/tests/test_models.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/199
> fix(grz-pydantic-models): prevent paired-end long read lab data

- packages/grz-pydantic-models/src/grz_pydantic_models/submission/metadata/v1.py
- tests/mock_files/metadata_validation/duplicate-run-id.json
- tests/test_parser.py
Also move sequencing file check into LabDatum to make sure that triggers first to prevent other test breakages.
Resolves https://github.com/BfArM-MVH/grz-tools/issues/211
Resolves https://github.com/BfArM-MVH/grz-tools/issues/25
> fix(grz-pydantic-models): ensure unique run IDs within a lab datum

- packages/grz-common/src/grz_common/validation/bam.py
- packages/grz-common/src/grz_common/validation/fastq.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/272
> fix(grz-common): reduce validation logging verbosity

- packages/grz-db/src/grz_db/models/submission.py
- tests/cli/test_db.py
> fix(grz-db): add StringConstraints to SubmissionBase.id

- packages/grz-db/src/grz_db/models/submission.py
- packages/grzctl/pyproject.toml
- packages/grzctl/src/grzctl/cli.py
- packages/grzctl/src/grzctl/commands/report.py
- tests/cli/test_report.py
> feat(grzctl): add reporting for processed submissions

- packages/grz-db/src/grz_db/models/submission.py
- packages/grzctl/src/grzctl/commands/__init__.py
- packages/grzctl/src/grzctl/commands/db.py
- packages/grzctl/src/grzctl/commands/list_submissions.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/340
feat(grz-db): add limit parameter to database list_submissions
> feat(grzctl): add configurable display limit for db list command

- packages/grzctl/src/grzctl/commands/list_submissions.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/343
fix(grzctl): display database state column if table empty but config provided
> feat(grzctl): replace oldest upload with duration in inbox list

- packages/grz-cli/src/grz_cli/cli.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/349
> feat(grz-cli): write command line to logs

- packages/grz-db/src/grz_db/models/author.py
- packages/grzctl/src/grzctl/commands/db.py
- packages/grzctl/tests/cli/test_db.py
Resolves https://github.com/BfArM-MVH/grz-tools/issues/318
fix(grz-db): allow empty author private key passphrases
> feat(grzctl): confirm before updating submission from error state

- packages/grzctl/src/grzctl/commands/pruefbericht.py
- tests/cli/test_pruefbericht.py
> fix(grzctl): refuse submission of pruefbericht with redacted tanG
